"""
Django settings for aquarium project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-maucqa@x#yl#eztj&d2vde682&4$2m7v_y0!zx^5@y$mft9xqu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'buyapp',
    'corsheaders',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.common.CommonMiddleware',
]
#以下也都先註解掉

#CSRF_COOKIE_NAME = 'csrftoken'
#CSRF_COOKIE_AGE = None
#CSRF_COOKIE_DOMAIN = None
#CSRF_COOKIE_PATH = '/'
#CSRF_COOKIE_SECURE = False
#CSRF_COOKIE_SAMESITE = 'Lax'
#CSRF_COOKIE_USED = True
#########


ROOT_URLCONF = 'aquarium.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aquarium.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = False

SECRET_KEY="kljliewurpqiuroqejrlkqejijuiol !iuooi;ujqwierujwqio;j;lkj;klj 9n vpuu1 ij1i;o uy89o ljq;oiu31 2v31ioj5 r;l31jerl;1u 32"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[BASE_DIR/'static',]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DEBUG = False

# SSL settings
# SSL_ENABLED = True
# SSL_CERT_PATH = '/home/seric/envdata/myproject/aquarium/cert.pem'
# SSL_KEY_PATH = '/home/seric/envdata/myproject/aquarium/key.pem'

#if SSL_ENABLED:
  #  # enable SSL settings
  #  os.environ['HTTPS'] = "on"
  #  os.environ['wsgi.url_scheme'] = 'https'
    
    # SSL certificate and key paths
   # SSL_CERT_PATH = SSL_CERT_PATH
    #SSL_KEY_PATH = SSL_KEY_PATH
    
    # SSL settings for runserver
    #RUNSERVER_SSL_OPTIONS = {
     #   'certfile': SSL_CERT_PATH,
     #   'keyfile': SSL_KEY_PATH,
     #   'ssl_requirement': {
     #       'https': 'on'
      #  }
   # }

    # SSL settings for production server (e.g. gunicorn, uwsgi)
    #下面這三行好像會一直重定向到https,但目前我是用http,所以會影響API端點的PUT功能
    #SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    #SECURE_SSL_REDIRECT = True
    #SSL_REDIRECT_STATUS = 301

# your other settings here...
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],

}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

CORS_ORIGIN_WHITELIST = [
    'http://example.com',
    'https://example.com',
    'http://192.168.0.1',
    'https://192.168.58.123',
]